#################
### UNIVERSAL ###
#################
$body_font = 20
$huge_font = 100
$heading_font = 50
$large_font = 30
$small_font = 15

################
### TOP LEFT ###
################
$top_left_offset = -260, 140
$pw_box_offset = -260, 540
$un_box_offset = -260, 660
$pw_text_offset = 520, 600
$un_text_offset = 520, 720
$login_text_offset = -260, 800
$hostname_text_offset = -260, 900
$un_value_offset = 520, 690
$input_field_offset = 500, 540
$top_left_size = 480
$container_box_size = 400, 100
$input_field_size = 400, 80

###################
### BOTTOM LEFT ###
###################
$bottom_left_offset = -260, -260
$time_text_offset = -260, -780
$uptime_ltext_offset = 580, 260
$uptime_rtext_offset = -1100, 260
$bottom_left_size = 240

#############
### RIGHT ###
#############
$right_offset = 260, 0
$right_bottom_box_offset = 260, 120
$network_box_offset = 150, 380
$bluetooth_box_offset = 370, 380
$power_box_offset = 260, 160
$image_offset = 260, 860
$media_symbol_offset = 260, -580
$network_symbol_offset = 150, 440
$bluetooth_symbol_offset = 370, 440
$day_value_offset = 260, 740
$date_value_offset = 260, 700
$media_content_value_offset = 260, -620
$media_player_value_offset = 260, -650
$network_value_offset = 150, 410
$bluetooth_value_offset = 370, 410
$power_status_value_offset = 260, 200
$power_percent_value_offset = 260, 220
$power_indicator_value_offset = 260, 280
$right_size = 480
$right_bottom_box_size = 480, 540
$power_box_size = 400, 180
$connection_box_size = 180, 120
