-- Hyprland Lua configuration for Desktop PC.
-- Migrated to native Hyprland Lua mode for 0.56+.
-- Always runs at maximum performance (no power management / switching).

local home = os.getenv("HOME")
local scripts = home .. "/.local/share/bin"

-- Outputs. Keep the AOC at 0x0 so portals and RustDesk treat it as primary.
hl.monitor({
    output = "desc:AOC CU34G2XP 1Q1S4HA000685",
    mode = "3440x1440@180.00",
    position = "0x0",
    scale = 1,
    bitdepth = 10,
    cm = "srgb",
})
hl.monitor({
    output = "desc:Microstep MSI G241 0x000002A7",
    mode = "1920x1080@60.00",
    position = "3440x0",
    scale = 1,
    cm = "srgb",
})
hl.workspace_rule({
    workspace = "1",
    monitor = "desc:AOC CU34G2XP 1Q1S4HA000685",
    default = true,
})
hl.workspace_rule({
    workspace = "2",
    monitor = "desc:Microstep MSI G241 0x000002A7",
    default = true,
})
hl.monitor({
    output = "",
    mode = "preferred",
    position = "5360x0",
    scale = 1,
})

-- Programs started once with the Hyprland session.
hl.on("hyprland.start", function()
    local commands = {
        scripts .. "/resetxdgportal.sh",
        "dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP",
        "dbus-update-activation-environment --systemd --all",
        "systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP",
        "systemctl --user restart vicinae.service",
        scripts .. "/polkitkdeauth.sh",
        "noctalia --daemon",
        "blueman-applet",
        "udiskie --no-automount --smart-tray",
        "nm-applet --indicator",
        "playerctl daemon",
    }
    for _, command in ipairs(commands) do
        hl.exec_cmd(command)
    end
end)

-- Load shared Hyprland configuration (layouts, theme, rules, common binds)
local common = require("common")
common.setup()

-- Keep the desktop SDR by default while allowing fullscreen HDR clients to switch.
hl.config({
    render = {
        cm_enabled = true,
        cm_auto_hdr = 1,
        send_content_type = true,
        use_fp16 = 2,
        keep_unmodified_copy = 2,
    },
})

-- Generated by the theme and animation selectors. These load last so a
-- user-selected profile can override the stable defaults above.
require("./overrides/theme")
require("./overrides/animation")

-- Keep this literal require in the entrypoint: Noctalia's template hook detects it.
common.apply_noctalia_theme(function()
    return require("noctalia")
end)
