[Server]
path = /home/semyon/.local/share/gns3-ct3531/bin/gns3server
host = 127.0.0.1
port = 3082
auto_start = True
auth = False
projects_path = /home/semyon/GNS3/projects
images_path = /home/semyon/GNS3/images
ubridge_path = /usr/bin/ubridge
report_errors = False
appliances_path = /home/semyon/GNS3/appliances
additional_images_paths = 
symbols_path = /home/semyon/GNS3/symbols
configs_path = /home/semyon/GNS3/configs
allow_console_from_anywhere = False
user = 
password = 
protocol = http
console_start_port_range = 5000
console_end_port_range = 10000
udp_start_port_range = 10000
udp_end_port_range = 20000

