general {
    lock_cmd = pidof hyprlock || hyprlock    # don't spawn multiple hyprlock instances
    before_sleep_cmd = loginctl lock-session  # lock before suspend
    after_sleep_cmd = hyprctl dispatch dpms on # turn screen back on after wake
    ignore_dbus_inhibit = false               # respect waybar caffeine (idle_inhibitor)
}

# dim screen after 4 minutes
listener {
    timeout = 240
    on-timeout = brightnessctl -s set 20%
    on-resume = brightnessctl -r
}

# pre-render hyprlock panels 30s before lock
listener {
    timeout = 270
    on-timeout = ~/.config/hypr/sakoora.hyprlock/hyprlock-run/panels
}

# lock screen after 5 minutes
listener {
    timeout = 300
    on-timeout = pidof hyprlock || hyprlock
}

# turn off display after 6 minutes
listener {
    timeout = 360
    on-timeout = hyprctl dispatch dpms off
    on-resume = hyprctl dispatch dpms on
}

# suspend after 30 minutes
listener {
    timeout = 1800
    on-timeout = systemctl suspend
}
